# my-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-aks
spec:
  replicas: 3
  selector:
    matchLabels:
      role: laravel-aks
  template:
    metadata:
      labels:
        role: laravel-aks
    spec:
      containers:
      - name: laravel-aks
        image: 97022702134/laravel-aks:v2
        ports:
        - containerPort: 80 # Puerto interno en el contenedor